- hosts: hosts
  become: true
  vars:
    vos_dir: "/data/vos"
    cluster_name: "k8s-develop"
    os_template_path: "/data/vos/centos/CentOS-8-GenericCloud-8.1.1911-20200113.3.x86_64.qcow2"
    nodes:
      - name: master-1
        cpu: 4
        mem: 4096
        mac: AC:DE:A5:10:00:01
        os_disk_size: 40G
      - name: node-1
        cpu: 8
        mem: 8192
        mac: AC:DE:A5:10:00:01
        os_disk_size: 40G

  roles:
  - libvirt
