- hosts: masters
  become: true

  vars:
    - k8s_version: "v1.22.0"
    - master_bins:
      - kubectl
      - kube-apiserver
      - kube-scheduler
      - kube-controller-manager
    - etcd_version: "v3.5.0"
    - etcd_internal_ip: "192.168.122.21"
    - kube_apiserver_ip: "192.168.122.21"

  pre_tasks:

  - name: set hostname to {{inventory_hostname}}
    hostname:
      name: "{{ inventory_hostname }}"

  - name: 禁用 selinux
    selinux:
      state: disabled

  - name: update centos
    yum:
      name: '*'
      state: latest

  - name: install basic repos
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - epel-release

  - name: install basic packages
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - NetworkManager
      - wget
      - vim
      - htop
      - dstat
      - lsof
      - tree
      - tmux
      - rsync
      # - ntp
      - chrony
      - socat
      - conntrack
      - ipset
      - chrony
      - net-tools
      - nfs-utils
      - ipvsadm
      - tcpdump
      - bind-utils
      - jq

  roles:
  - kfs-master
