- hosts: nodes
  become: true

  vars:
    - container_runtime: "docker"
    - cni_plugins_version: "v0.8.7"

  pre_tasks:

  - name: set hostname to {{inventory_hostname}}
    hostname:
      name: "{{ inventory_hostname }}"

  - name: 禁用 selinux
    selinux:
      state: disabled

  - name: update centos
    yum:
      name: '*'
      state: latest

  - name: install basic repos
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - epel-release

  - name: install basic packages
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - NetworkManager
      - wget
      - vim
      - htop
      - dstat
      - lsof
      - tree
      - tmux
      - rsync
      # - ntp
      - chrony
      - socat
      - conntrack
      - ipset
      - chrony
      - net-tools
      - nfs-utils
      - ipvsadm
      - tcpdump
      - bind-utils
      - iptables
      # rook ceph 依赖此工具
      - lvm2

  roles:
  - kfs-node
